### ISSUE TITLE
skin changing

### ISSUE THREAD

**Issue by bencxz0** [zatrit/openmcskins2#18]
when i use the mod my skin changes to a slim skin

**Comment by zatrit** [comment]
Send your config

**Comment by bencxz0** [comment]
the config file?

**Comment by bencxz0** [comment]
actually i removed the mod

**Comment by bencxz0** [comment]
because of this bug

**Comment by bencxz0** [comment]
i hate slim skins

**Comment by bencxz0** [comment]
but it continues to happen even if i download it again

**Comment by zatrit** [comment]
What's in your ``.minecraft/config/openmcskins.toml`` file?

**Comment by zatrit** [comment]
To understand why you are experiencing this bug, I need at least your config and logs
