### ISSUE TITLE
1.20.1 support when? and a question

### ISSUE THREAD

**Issue by jwaxy** [zatrit/openmcskins2#2]
Hello! This looks like a great project but I have two questions:

1. Will/When there be 1.20.1 support?
2. How is this mod diffrent from [that](https://www.curseforge.com/minecraft/mc-mods/customskinloader) mod? Only extra capes and ears support?

**Comment by zatrit** [comment]
1. OpenMCSkins 2.0 works fine on 1.20.1, but I'm not sure of the release date. OpenMCSkins 1.3 will not be upgraded to 1.20.*
2. The ears have not yet been implemented for now. OpenMCSkins (at least version 1.*) supported custom models. And I'm also working on a preset system to allow flexible customization of skins and even add new skin sources (e.g. those where skins can be found via a link like https://example.com/skin/{name}.png). OpenMCSkins 2.0 is still under development and a lot of functionality has not been implemented yet, but I am actively working on it

**Comment by jwaxy** [comment]
ok thx

**Comment by zatrit** [comment]
You're welcome
