### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by ManInMyVan** [zatrit/openmcskins2#20]

**Comment by ManInMyVan** [comment]
9888cbc

**Comment by zatrit** [comment]
It's currently only workaround and there's still lots of work to do to make this work on 1.20.4

**Comment by rakantoh** [comment]
how can i use/download the updated version for 1.20.4?

**Comment by zatrit** [comment]
There is currently no working version 1.20.4 of OpenMCSkins, and I hope to be able to get it working when I have enough time (I'm working on a school project right now)

**Comment by rakantoh** [comment]
> There is currently no working version 1.20.4 of OpenMCSkins, and I hope to be able to get it working when I have enough time (I'm working on a school project right now)

ohh ok, then i will wait, thanks

**Comment by zatrit** [comment]
3aab336
