### ISSUE TITLE
how to load a custom skin for myself?

### ISSUE THREAD

**Issue by Useott** [zatrit/openmcskins2#23]
I tried using `/omcs add local` and adding my skin to config/openmcskins/local but it didn't work

**Comment by zatrit** [comment]
[This file](https://github.com/zatrit/openmcskins2/blob/main/docs/localResolverHierarchy.md) describes the hierarchy for the local resolver. Did you put your skin according to it?

**Comment by Useott** [comment]
I wasn't aware of that. Thanks!
